name: Reusable workflow example
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: run the command
        run: |
         echo "Hello ${{ inputs.message }}"
