name: demo workflow

on: [ push ]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: run the command
        run: echo "Hello World"

